### ISSUE TITLE
I love you.

### ISSUE THREAD

**Issue by 19h** [gisjedi/dcos-templates#1]
Hey,

thanks a lot for your templates. We've been spending a few days on getting NFS working with the cloud-config. Please make this more prominent or share this with the DC/OS community :-)

Should you ever be in Berlin, come along for a beer on us

🍻

**Comment by gisjedi** [comment]
:-) Glad you found this useful.  It took me much longer than it should have to get this working, so I hope I was able to save you some time.  I did submit this back to the Mesosphere folks, but I don't expect them to adopt NFS into their master templates as that is fairly deployment specific. 

Please do share for others that may benefit from this.
